# NumPy 

You can install numpy in your anaconda environment using command 'conda install numpy'. However it comes preinstalled with Anaconda Distribution

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

# Numpy Arrays
Used majorly for linear Algebra (Arrays).

Numpy arrays essentially come in two flavors: vectors and matrices. 
Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).


## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [10]:
my_list = [1,2,3]

In [11]:
my_list

[1, 2, 3]

In [15]:
np.array(my_list)

array([1, 2, 3])

In [16]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [2]:
np.random.rand(2)

array([0.12522648, 0.34284711])

In [3]:
np.random.rand(5,5)

array([[0.21384762, 0.69327707, 0.81946733, 0.37656463, 0.54314898],
       [0.56442376, 0.16114218, 0.67497218, 0.85298982, 0.00959824],
       [0.18012437, 0.52313761, 0.55584972, 0.21084084, 0.62160672],
       [0.43686454, 0.76775842, 0.97545166, 0.39190616, 0.34702421],
       [0.87158148, 0.78348518, 0.99381709, 0.59377312, 0.08407192]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [4]:
np.random.randn(2)

array([-1.12512647, -0.05411063])

In [5]:
np.random.randn(5,5)

array([[-0.65622217,  1.02802913, -1.08958385,  0.05187879,  0.69482143],
       [-0.77470529, -1.36619799, -0.10089356, -0.06262755,  0.95778996],
       [-0.48473009,  0.16980479, -0.29471115,  1.04461375, -1.48273776],
       [-1.34096877, -0.8535658 ,  0.56854022, -0.76092772,  0.5023414 ],
       [-0.90135014,  0.99929458, -0.14885085, -0.3071196 ,  0.46928575]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [46]:
np.random.randint(1,100)

73

In [47]:
np.random.randint(1,100,10)

array([44, 22, 68, 52, 48, 20, 83, 30, 70, 40])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [6]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ranarr

array([20, 35,  1, 41, 15, 10, 11,  5, 12, 35])

## Reshape
Returns an array containing the same data with a new shape.

In [52]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [53]:
ranarr

array([20, 35,  1, 41, 15, 10, 11,  5, 12, 35])

In [54]:
ranarr.max()

41

In [55]:
ranarr.argmax()

3

In [57]:
ranarr.min()

1

In [58]:
ranarr.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
# Vector
arr.shape

(25,)

In [70]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [73]:
arr.reshape(1,25).shape

(1, 25)

In [74]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [76]:
arr.dtype

dtype('int32')