# NumPy Indexing and Selection

In [2]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5],arr[6], arr[4]

(5, 6, 4)

In [8]:
arr[-1]

10

In [9]:
arr[-2]

9

In [11]:
#Everything but the last element
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [19]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
#Or you can use any expression as well
arr[0:5] = arr[0:5]*3
arr

array([300, 300, 300, 300, 300,   5,   6,   7,   8,   9,  10])

In [21]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Array Slicing is in-place function so be careful! 
**Data is not copied, it's a view of the original array! This avoids memory problems!**

In [22]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [23]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Data is not copied, it's a view of the original array! This avoids memory problems!**

In [25]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
#and arr is:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Now if i change the copied array by broadcasting it, it will change the copied array and not the original one**

In [28]:
#to change all elements using broadcasting
#arr_copy[:] = 100
#or to change selective elements
arr_copy[0:6] = [0,1,2,3,4,5]
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#and checking the original array 'arr'
arr
#This shall still be the same.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [30]:
#You can create a 2d-array using arange and reshape function
#a = np.arange(1,26)
#arr_2d = a.reshape(5,5)
#arr_2d

In [31]:
#Or you can do that using lists as well as shown below

In [32]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [8]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [9]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [10]:
# Getting individual element value
arr_2d[1,0]

20

In [18]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [20]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Extended Slicing
If you wish to grab middle elements and not the adjacent elements <br>
You can use :: (double colon), also called as extended slicing<br>
#### Python sequence slice addresses can be written as a[start:end:step] and any of start, stop or end can be dropped.  a[::3] is every third element of the sequence.

In [52]:
a = np.arange(1,26)
arr2 = a.reshape(5,5)
arr2

#Alternatively you can use directly
#arr2 = np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
#e.g. To select all even rows indexed rowsn and even indexed columns
arr2[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [48]:
#e.g. to select all odd indexed rows and odd indexed columns
arr2[1::2,1::2]

array([[ 7,  9],
       [17, 19]])

In [49]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
#Lets say you want to grab any random part of 2d array
#[ 7,  9]
#[22, 24]]
arr2[1::3, 1::2]

array([[ 7,  9],
       [22, 24]])

**Explanation of above section:**<br>
**Row:** You wanted to grab 7,9 and 22,24 which are rows at index 1st and 4th respectively. So to achieve that you started at index 1 (1::) and put the step size of 3 (1::3) and you get two rows: <br>
6,7,8,9,10
21,22,23,24,25<br>
**Columns:** You wanted to grab 7,9 and 22,24 which are columns at index 1st and 3rd respectively for each pair. Hence you started with index 1(1::) and put the step size of 2(1::2) so you get the third column as well.<br>
**Hence the result**


### Fancy Indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays

In [13]:
arr = np.random.randint(1,50, size=32).reshape((8,4))

In [14]:
arr

array([[ 9, 38, 10, 19],
       [37, 20, 16, 10],
       [36, 44, 28,  4],
       [ 4, 45, 16, 21],
       [25, 32, 28,  5],
       [10, 14,  4, 12],
       [21, 47, 16, 32],
       [15, 25, 13, 37]])

To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order:

In [19]:
arr[[4, 3, 0, 6]]

array([[25, 32, 28,  5],
       [ 4, 45, 16, 21],
       [ 9, 38, 10, 19],
       [21, 47, 16, 32]])

In [20]:
#The above command is equivalent to: 
arr[[4, 3, 0, 6], :]

array([[25, 32, 28,  5],
       [ 4, 45, 16, 21],
       [ 9, 38, 10, 19],
       [21, 47, 16, 32]])

In [36]:
#To select the columns as well (but this is limited approach
#for columns)
arr[[4, 3, 0, 6], 0:2]

array([[25, 32],
       [ 4, 45],
       [ 9, 38],
       [21, 47]])

In [37]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[37, 10, 20, 16],
       [10, 12, 14,  4],
       [15, 37, 25, 13],
       [36,  4, 44, 28]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [50]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])