# NumPy Operations

## 1. Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [2]:
import numpy as np
arr = np.arange(0,10)

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
# Also warning, but not an error instead infinity
1/arr

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [9]:
arr > arr

array([False, False, False, False, False, False, False, False, False,
       False])

In [11]:
arr <= arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [12]:
arr < arr

array([False, False, False, False, False, False, False, False, False,
       False])

In [13]:
arr != arr

array([False, False, False, False, False, False, False, False, False,
       False])

In [14]:
arr[arr % 2]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

## 2. Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything. Arrays have the transpose method and also the special T attribute

**Transpose**

In [15]:
arr = np.arange(15).reshape((3, 5))

In [16]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

**dot product**

In [18]:
arr = np.random.randn(6, 3)

In [21]:
arr

array([[ 0.26776814, -1.37788967, -0.54441479],
       [-1.86335249,  1.30122616, -0.81671509],
       [-0.05714267,  1.40420491, -0.65973198],
       [-0.79519892, -0.58062859,  0.1799575 ],
       [-1.27875688, -0.15676564,  1.52730296],
       [-1.30187423, -0.60746435,  0.00647644]])

In [20]:
np.dot(arr.T, arr)

array([[ 7.50948456, -1.42081542, -0.69083267],
       [-1.42081542,  6.29427887, -1.58683773],
       [-0.69083267, -1.58683773,  3.76373826]])

In [24]:
arr = np.arange(16).reshape((2, 2, 4))

In [26]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [34]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 3. Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [35]:
#Taking Square Roots
np.sqrt(arr)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131]],

       [[2.82842712, 3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739, 3.87298335]]])

In [36]:
#Calcualting exponential (e^)
np.exp(arr)

array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03]],

       [[2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
        [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]]])

In [37]:
np.max(arr) #same as arr.max()

15

In [38]:
np.sin(arr)

array([[[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ]],

       [[ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
        [-0.53657292,  0.42016704,  0.99060736,  0.65028784]]])

In [39]:
np.log(arr)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[[      -inf, 0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947, 1.94591015]],

       [[2.07944154, 2.19722458, 2.30258509, 2.39789527],
        [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]]])

### Unary ufuncs & Binary ufuncs
A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. 

**unary ufuncs**: You can think of them as fast vectorized wrappers for simplefunctions that take one or more scalar values and produce one or more scalar results.These are referred to as **unary ufuncs**. 

**binary ufuncs**: Others, such as add or maximum, take two arrays (thus, binary ufuncs) and return a single array as the result

#### abs() vs fabs()
The difference is that **np.fabs(number) will always return a floating point number** even if the argument is integer, whereas **np.abs() will return a floating point or an integer depending** upon the argument.

In [46]:
np.fabs(-536)

536.0

In [53]:
np.abs(-563)

563

In [58]:
np.square([3,4,5])

array([ 9, 16, 25], dtype=int32)

**Numpy Unary ufuncs are**
- abs, fabs
- sqrt
- square (Square of number/array)
- exp
- log, log10, log2, log1p (Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively)
- sign (Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative))
- ceil (Compute the ceiling of each element (i.e. 3.14 = 4))
- floor (Compute the floor of each element, e.g. 7.8 = 7)
- rint (Round elements to the nearest integer, preserving the dtype)
- modf (Return fractional and integral parts of array as a separate array)
- isnan (Return boolean array indicating whether each value is NaN (Not a Number))
- isfinite, isinf (Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively)
- cos, cosh, sin, sinh, tan, tanh(Regular and hyperbolic trigonometric functions)
- arccos, arccosh, arcsin, arcsinh, arctan, arctanh (Inverse trigonometric functions)
- logical_not (Compute truth value of not x element-wise (equivalent to ~arr).)

**Numpy binay ufuncs**
- add (Add corresponding elements in two arrays)
- subtract (Subtract elements in second array from first array)
- multiply (Multiply two array elements)
- divide, floor_divide (Divide or floor divide (truncating the remainder))
- power (Raise elements in first array to powers indicated in second array)
- maximum, fmax (Element-wise maximum; fmax ignores NaN)
- minimum, fmin (Element-wise minimum; fmin ignores NaN)
- mod (Element-wise modulus (remainder of division))
- copysign (Copy sign of values in second argument to values in first argument)

In [64]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

## 4. Mathematical & Statistical Methods

In [65]:
#Lets create an array first
arr = np.random.randn(5, 4)

In [66]:
arr

array([[ 2.8071946 ,  1.06110474,  0.2587537 ,  1.25979874],
       [ 1.11986902, -1.10679386,  2.81407824,  1.24860658],
       [ 1.71327095,  0.55376752,  0.47344502, -0.14947357],
       [ 0.65157307,  0.0854021 , -0.22991004, -0.30766086],
       [ 0.44224416, -0.16662826,  1.07383865,  0.56652394]])

**4.1 mean():**

In [73]:
#4.1 mean()
arr.mean()
#optional parameter 'axis', 0 = columns, 1=rows
#arr.mean(axis = 0)

0.7084502218869619

In [75]:
#or alternatively
np.mean(arr)
#np.mean(arr, axis=0)

0.7084502218869619

**4.2 sum():**

In [79]:
#4.2 sum()
np.sum(arr)
#np.sum(arr, 0)
#optional parameter 'axis', 0=column, 1=row

14.169004437739238

In [81]:
arr.sum()
#arr.sum(0) optional parameter 'axis'

14.169004437739238

**4.3 cumsum(): cumulative sum**

In [82]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [84]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [86]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [91]:
#For multidimension arrays:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [92]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [98]:
arr.cumsum(axis=0) #along columns
arr.cumsum(axis=1) #along rows

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [100]:
print(np.cumsum(arr, axis=0)) #along columns
print("---")
print(np.cumsum(arr, axis=1)) #along rows

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
---
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


**4.4 cumprod(): cumulative product**

In [101]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [102]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [103]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [106]:
np.cumproduct(arr,axis=0) #same as cumprod()

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

In [109]:
np.cumprod(arr,axis=0) #same as cumproduct()

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

**Basic Array Stats methods**

- sum
- mean
- std
- var
- min
- max
- argmin
- argmax
- cumsum
- cumprod

# 5. Sorting & others

### 5.1 Sorting

In [121]:
arr = np.random.randn(6).round(3)

In [122]:
arr

array([ 0.311,  0.248,  0.095, -0.161,  1.757, -1.251])

In [123]:
arr.sort()

In [124]:
#or using Numpy
np.sort(arr)

array([-1.251, -0.161,  0.095,  0.248,  0.311,  1.757])

In [125]:
arr2 = np.random.randn(36).reshape(6,6).round(3)

In [126]:
arr2

array([[ 0.073, -0.348, -0.224,  0.678, -0.349,  0.4  ],
       [-0.889, -0.293, -0.805, -0.446,  0.441, -1.604],
       [ 0.037,  0.661,  0.712,  0.85 , -2.095, -0.623],
       [-0.573,  0.125,  1.603, -0.416,  0.533, -0.007],
       [-0.468,  2.071,  0.187, -0.509,  0.244, -1.319],
       [-0.219, -0.944, -0.392, -0.949, -1.623, -0.795]])

In [130]:
np.sort(arr2, axis=1) #sorts each element within same list only
#axis is optional

array([[-0.349, -0.348, -0.224,  0.073,  0.4  ,  0.678],
       [-1.604, -0.889, -0.805, -0.446, -0.293,  0.441],
       [-2.095, -0.623,  0.037,  0.661,  0.712,  0.85 ],
       [-0.573, -0.416, -0.007,  0.125,  0.533,  1.603],
       [-1.319, -0.509, -0.468,  0.187,  0.244,  2.071],
       [-1.623, -0.949, -0.944, -0.795, -0.392, -0.219]])

### 5.2 unique

In [131]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [132]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [133]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [134]:
np.unique(ints)

array([1, 2, 3, 4])

In [135]:
#Pure python alternative for this one is: 
sorted(set(names))

['Bob', 'Joe', 'Will']

# 6. Linear Algebra
Linear algebra, like matrix multiplication, decompositions, determinants, and other square matrix math, is an important part of any array library. Unlike some languages like MATLAB, multiplying two two-dimensional arrays with * is an element-wise
product instead of a matrix dot product. Thus, there is a function dot, both an array method and a function in the numpy namespace, for matrix multiplication

In [136]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [137]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [138]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [139]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

#### 6.1 Matrix Multiplication

In [140]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [141]:
#Alternatively
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

**Note:**
np.dot() is a matrix multiplication if both a and b are 2-D arrays, but using matmul or a @ b is preferred.
@ - also works as an infix operator

In [144]:
x @ y

array([[ 28.,  64.],
       [ 67., 181.]])

In [145]:
np.matmul(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

#### 6.2 numpy.linalg (Advance Part)

numpy.linalg has a standard set of matrix decompositions and things like inverse and determinant. These are implemented under the hood via the same industrystandard linear algebra libraries used in other languages like MATLAB and R, such as BLAS, LAPACK, or possibly (depending on your NumPy build) the proprietary Intel MKL (Math Kernel Library)

In [146]:
from numpy.linalg import inv, qr

In [150]:
X = np.random.randn(3, 3).round(2)

In [151]:
mat = X.T.dot(X)

In [152]:
mat

array([[ 0.6334, -0.5892, -0.5045],
       [-0.5892,  4.7566,  1.7611],
       [-0.5045,  1.7611,  0.7998]])

In [153]:
inv(mat)

array([[ 182.05700877, -108.07364665,  352.80852718],
       [-108.07364665,   65.29318057, -211.94170422],
       [ 352.80852718, -211.94170422,  690.47566549]])

In [155]:
#Multiplication of a matrix and its inverse is identity matrix
mat.dot(inv(mat)).round(2)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
#q, r factorization of matrix
q, r = qr(mat)

In [157]:
q

array([[-0.63249225, -0.63821175,  0.43890696],
       [ 0.58835559, -0.76440782, -0.26366338],
       [ 0.50377698,  0.09146832,  0.85897747]])

In [158]:
r

array([[-1.00143520e+00,  4.05843830e+00,  1.75816621e+00],
       [ 0.00000000e+00, -3.09886301e+00, -9.51064423e-01],
       [ 0.00000000e+00,  0.00000000e+00,  1.24403729e-03]])

#### 6.3 Distributions using Numpy

**Some of the numpy random functions**
- permutation (Return a random permutation of a sequence, or return a permuted range)
- shuffle (Randomly permute a sequence in-place)
- rand (Draw samples from a uniform distribution)
- randint (Draw random integers from a given low-to-high range)
- randn (Draw samples from a normal distribution with mean 0 and standard deviation 1 (MATLAB-like interface))
- binomial (Draw samples from a binomial distribution)
- normal (Draw samples from a normal (Gaussian) distribution)
- beta (Draw samples from a beta distribution)
- chisquare (Draw samples from a chi-square distribution)
- gamma (Draw samples from a gamma distribution)
- uniform (Draw samples from a uniform [0, 1) distribution)

In [164]:
np.random.chisquare(df=3,size=10)
#df = degree of freedom

array([1.8457934 , 2.7931956 , 2.23122132, 1.26783125, 0.31887503,
       1.16496671, 0.18603856, 1.42325728, 1.03276325, 4.38790363])

In [167]:
np.random.normal(loc=0,scale=1,size=10)
#mean=0, standard dev = 1, samples = 10

array([ 0.53909946,  0.20402411, -1.0264133 ,  1.50916757,  0.86238313,
        0.74179631, -0.47371322,  0.18025281, -2.4527887 ,  0.1005969 ])